"""add skills table

Revision ID: 3ef750036d1c
Revises: 20260424_0001
Create Date: 2026-04-25 00:20:52.197360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef750036d1c'
down_revision: Union[str, None] = '20260424_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_room_id'), 'skills', ['room_id'], unique=False)
    op.create_index(op.f('ix_decision_relations_decision_id'), 'decision_relations', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_relations_related_decision_id'), 'decision_relations', ['related_decision_id'], unique=False)
    op.create_index(op.f('ix_votes_conflict_id'), 'votes', ['conflict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_conflict_id'), table_name='votes')
    op.drop_index(op.f('ix_decision_relations_related_decision_id'), table_name='decision_relations')
    op.drop_index(op.f('ix_decision_relations_decision_id'), table_name='decision_relations')
    op.drop_index(op.f('ix_skills_room_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
